[project]
name = "abantether-python-sdk"
version = "0.0.1"
authors = [
  { name="Iman Mousaei", email="imanmousaei1379@gmail.com" },
]
description = "A python sdk to trade easily in abantether.com"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Abantether-com/abantether-python-sdk/"
Issues = "https://github.com/Abantether-com/abantether-python-sdk/issues"